---
- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
- name: restart-auditbeat
  service:
    name: auditbeat
    state: restarted
- name: restart-auditbeat-windows
  win_shell: Restart-Service auditbeat
